# Generated by Django 5.1.5 on 2025-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_payment_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref',
            field=models.CharField(default='aasasassasdaasasdASD', max_length=255),
            preserve_default=False,
        ),
    ]
