# Generated by Django 5.1.5 on 2025-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'completed'), ('failed', 'Failed')], max_length=10),
        ),
    ]
