# Generated by Django 5.1.5 on 2025-03-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_order_orderitem_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
