# Generated by Django 5.1.5 on 2025-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
