# Generated by Django 5.1.5 on 2025-02-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='../static/images/default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
