# Generated by Django 5.1.5 on 2025-03-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0007_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternate_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
