# Generated by Django 5.1.5 on 2025-09-01 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auths', '0014_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
