# Generated by Django 5.1.5 on 2025-04-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatSupport', '0004_alter_chatroom_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messagereadstatus',
            options={'verbose_name_plural': 'Message Statuses'},
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='chat_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_read_status', to='ChatSupport.chatroom'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='staff_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
