# Generated by Django 5.1.5 on 2025-02-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='possible_accompaniments',
            field=models.ManyToManyField(null=True, related_name='products', to='Products.accompaniment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(null=True, related_name='products', to='Products.productcategory'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_category',
        ),
        migrations.AddField(
            model_name='product',
            name='shop_category',
            field=models.ManyToManyField(null=True, related_name='products', to='Products.shopcategory'),
        ),
    ]
