# Generated by Django 5.1.5 on 2025-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_possible_accompaniments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='possible_accompaniments',
            field=models.ManyToManyField(blank=True, related_name='products', to='Products.accompaniment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(blank=True, related_name='products', to='Products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_category',
            field=models.ManyToManyField(blank=True, related_name='products', to='Products.shopcategory'),
        ),
    ]
