# Generated by Django 5.1.5 on 2025-02-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_possible_accompaniments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.PositiveIntegerField(blank=True, help_text='Time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pick_and_go',
            field=models.BooleanField(default=False),
        ),
    ]
