# Generated by Django 5.1.5 on 2025-03-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0006_remove_orderitem_order_remove_orderitem_product_and_more'),
        ('Products', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payments.payment'),
        ),
    ]
