# Generated by Django 5.1.5 on 2025-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_order_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompaniment',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=10),
        ),
    ]
