# Generated by Django 5.1.5 on 2025-08-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_order_products_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Products.product')),
            ],
        ),
    ]
