# Generated by Django 5.1.5 on 2025-09-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_orderpickuplocations_order_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clients_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
